# Generated by Django 4.2.15 on 2024-09-02 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_number_of_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_guest',
            new_name='number_of_guests',
        ),
    ]
