# Generated by Django 4.2.15 on 2024-09-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_number_of_guest_reservation_number_of_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
